# .fuzz_token.yml

fuzz:
    # Tell the CLI where to find the compiled contracts and compilation artifacts
    build_directory: artifacts
    ide: "hardhat"
    map_to_original_source: true 
    
    # We'll do fuzzing with 2 cores 🚀
    number_of_cores: 4
  
    # Run the campaign for just 10 minutes
    time_limit: 60m 

    # Put the campaign in the Sribble Exercise 1 project
    project: "Shorter test"
    
    # When the campaign is created it'll get a name <prefix>_<random_characters>
    campaign_name_prefix: "ShorterV1"
    # Point to your ganache node which holds the seed 🌱
    rpc_url: "http://localhost:8545"

    key: "MXczMzBnN1NUVFJmRU5PUTh0QUlwT0s4S005d2ZnWmY6OmRpbGlnZW5jZS51cy5hdXRoMC5jb20=::v1.MbdODrgaFRlvdSI8qhHwH6Q09BF9-rCjgwNbpzabu4GnqfvU7fFmQK64BgfsH4gn7AmU2s5ny3t_b9FgmDsegEA"

    # This is the contract that the campaign will show coverage for/ map issues to etc
    # It's a list of all the relevant contracts (don't worry about dependencies, we'll get those automatically 🙌)
    targets:
        - "contracts/ShorterFactory.sol"
        # - "contracts/ShorterBone.sol"
        # - "contracts/DexCenter.sol"
        # - "contracts/v1/VaultButlerImpl.sol"
        # - "contracts/v1/TreasuryImpl.sol"
        # - "contracts/v1/TradingHubImpl.sol"
        # - "contracts/v1/Rescuable.sol"
        # - "contracts/v1/PoolScatter.sol"
        # - "contracts/v1/PoolGuardianImpl.sol"
        # - "contracts/v1/PoolGarner.sol"
        # - "contracts/v1/IpistrTokenImpl.sol"
        # - "contracts/v1/FarmingImpl.sol"
        # - "contracts/v1/CommitteeImpl.sol"
        # - "contracts/v1/AuctionHallImpl.sol"
        # # Oracles
        # - "contracts/oracles/PriceOracle.sol"
        # # Tokens
        # - "contracts/tokens/ERC20.sol"
        # # Util
        # - "contracts/util/Ownable.sol"
        # - "contracts/util/Pausable.sol"
        # - "contracts/util/Whitelistable.sol"
        # # Model
        # - "contracts/model/PoolRewardModel.sol"
        # - "contracts/model/VoteRewardModel.sol"
        # - "contracts/model/TradingRewardModel.sol"
        # - "contracts/model/InterestRateModel.sol"
        # - "contracts/model/GovRewardModel.sol"
        # - "contracts/model/FarmingRewardModel.sol"
        # # Proxy
        # - "contracts/proxy/AuctionHall.sol"
        # - "contracts/proxy/Farming.sol"
        # - "contracts/proxy/PoolGuardian.sol"
        # - "contracts/proxy/TradingHub.sol"
        # - "contracts/proxy/Treasury.sol"
        # - "contracts/proxy/VaultButler.sol"
        # # Governance
        # - "contracts/governance/Committee.sol"
        # - "contracts/governance/IpistrToken.sol"
        # # v1 Dexcenters
        # - "contracts/v1/dexcenters/BaseDexCenter.sol"
        # - "contracts/v1/dexcenters/UniClassDexCenter.sol"
        # # v1 Packager
        # - "contracts/v1/packager/Grandetie.sol"
        # - "contracts/v1/packager/GrandetieImpl.sol"
        # - "contracts/v1/packager/WrappedTokenImpl.sol"
        # - "contracts/v1/packager/WrapRouter.sol"
        # - "contracts/v1/packager/WrappedToken.sol"
        # # v1 Model
        # - "contracts/v1/model/PoolRewardModelImpl.sol"
        # - "contracts/v1/model/VoteRewardModelImpl.sol"
        # - "contracts/v1/model/TradingRewardModelImpl.sol"
        # - "contracts/v1/model/InterestRateModelImpl.sol"
        # - "contracts/v1/model/GovRewardModelImpl.sol"
        # - "contracts/v1/model/FarmingRewardModelImpl.sol"